name = "jvc-boucled-worker"
main = "src/index.ts"
compatibility_date = "2024-08-06"
compatibility_flags = [ "nodejs_compat" ]
send_metrics = false

[site]
bucket = "./public"

[triggers]
# Schedule cron triggers:
# - Every thirty minutes
# - Every six hours
# - Every minute
crons = [ "*/30 * * * *", "0 */6 * * *", "* * * * *" ]