import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SUCCESSFULL_ACCOUNT_ADDING = 0;
const FAILED_ACCOUNT_ADDING = 1;
const INEXISTENT_ACCOUNT = 2;
const WRONG_PASSWORD = 3;
const ACCOUNT_ALREADY_REGISTERED = 4;
const JVC_COOLDOWN = 5;
const JSON_ACCOUNTS_PATH = path.join(__dirname, '..', '..', 'data', 'accounts.json');
const JSON_LOOPS_PATH = path.join(__dirname, '..', '..', 'data', 'loops.json');
const LOGS_PATH = path.join(__dirname, '..', '..', 'logs', 'logs.log');
const SERVER_LOGS_PATH = path.join(__dirname, '..', '..', 'logs', 'server_logs.json');
const SUCCESSFULL_LOOP_ADDING = 0;
const FAILED_LOOP_ADDING = 1;
const LOOP_NAME_REDUNDANT = 2;
const LOOP_TIME_REDUNDANT = 3;
const INEXISTENT_LOOP_FORUM = 4;
const EMPTY_LOOP_DATA = 5;
const INVALID_CHAR = 6;
const ACCOUNTS_UPDATES_PER_DAY = 6;
const JSON_ERROR = 6;
const DAY_MS = 24*60*60*1000;
const POST_SUCCESS = 0;
const POST_FAILED = 1;
const NO_ACCOUNT_AVAILABLE = 2;
const TOPIC_DELETED = 3;
const ACCOUNT_BANNED = 4;
const NOT_CONNECTED = 5;
const RESOURCE_UNAVAILABLE = 6;
const INSUFFICIENT_LEVEL = 7;
const POSTER_TOO_FAST = 8;
const ALL_ACCOUNTS_USED = 9;
const TOO_MANY_RETRIES = 10;
const DELAY_BETWEEN_LOOPS_CHECK_MS = 60000;
const LOGIN_FAILED = 11;
const LOGIN_SUCCESS = 0;
const DELETION_SUCCESS = 0;
const DELETION_FAILED = 1;
const REQUEST_FAILED = 10;
const REQUEST_SUCCESS = 0;
const UPDATE_SUCCESS = 0;
const UPDATE_FAILED = 1;
const UPDATE_DELAY_BETWEEN_REQUESTS_MS = 50;

export { INEXISTENT_ACCOUNT, WRONG_PASSWORD, JSON_ACCOUNTS_PATH, ACCOUNTS_UPDATES_PER_DAY,
    SUCCESSFULL_ACCOUNT_ADDING, FAILED_ACCOUNT_ADDING, LOGS_PATH, EMPTY_LOOP_DATA, TOO_MANY_RETRIES,
    ACCOUNT_ALREADY_REGISTERED, JSON_LOOPS_PATH, SUCCESSFULL_LOOP_ADDING, DAY_MS, INVALID_CHAR,
    FAILED_LOOP_ADDING, JSON_ERROR, NO_ACCOUNT_AVAILABLE, LOOP_NAME_REDUNDANT, POST_FAILED, JVC_COOLDOWN,
    LOOP_TIME_REDUNDANT, INEXISTENT_LOOP_FORUM, POST_SUCCESS, INSUFFICIENT_LEVEL, TOPIC_DELETED,
    ACCOUNT_BANNED, NOT_CONNECTED, RESOURCE_UNAVAILABLE, POSTER_TOO_FAST, ALL_ACCOUNTS_USED,
    DELAY_BETWEEN_LOOPS_CHECK_MS, SERVER_LOGS_PATH, LOGIN_FAILED, LOGIN_SUCCESS, DELETION_SUCCESS,
    DELETION_FAILED, REQUEST_FAILED, REQUEST_SUCCESS, UPDATE_FAILED, UPDATE_SUCCESS, UPDATE_DELAY_BETWEEN_REQUESTS_MS };
